name: Build vLLM
run-name: Build vLLM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Publish artifacts produced by this job'
        required: false
        type: boolean
        default: false
      pushLatest:
        description: 'Tag artifacts produced by this job as latest-*'
        required: false
        type: boolean
        default: false
      releaseTag:
        description: 'Release tag'
        required: false
        type: string

jobs:
  build_native_linux_cpu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERBUILDBOT_USERNAME }}
        password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: "lab:latest"
        driver: cloud
        endpoint: "docker/make-product-smarter"
        install: true

    - name: Build generic vLLM
      uses: docker/build-push-action@v5
      with:
        file: ${{ github.workspace }}generic.Dockerfile
        platforms: linux/amd64, linux/arm64
        context: ${{ github.workspace }}
        build-args: |
          "BASE_IMAGE="ubuntu:24.04"
        push: false
        sbom: true
        provenance: mode=max
        outputs: type=local,dest=${{ github.workspace }}/out

  build_native_linux_cuda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERBUILDBOT_USERNAME }}
        password: ${{ secrets.DOCKERBUILDBOT_WRITE_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: "lab:latest"
        driver: cloud
        endpoint: "docker/make-product-smarter"
        install: true

    - name: Build CUDA accelerated vLLM
      uses: docker/build-push-action@v5
      with:
        file: ${{ github.workspace }}/cuda.Dockerfile
        platforms: linux/amd64, linux/arm64
        context: ${{ github.workspace }}/native
        build-args: |
          "CUDA_VERSION=12.9.0"
          "CUDA_IMAGE_VARIANT=ubuntu24.04"
        push: false
        sbom: true
        provenance: mode=max
        outputs: type=local,dest=${{ github.workspace }}/out

